<a href="https://colab.research.google.com/github/Bolgrmas13/Math311_Linear_Algebra_Projects/blob/main/Copy_of_Gram_Schmidt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [4]:
# Let's make a vector..... not happening.
# How about a matrix?
zz = np.matrix('1; 2; 3; 4')
zz

matrix([[1],
        [2],
        [3],
        [4]])

In [5]:
#Can we scale?
5*zz

matrix([[ 5],
        [10],
        [15],
        [20]])

In [6]:
# is there a dot product?
zz.dot(zz)

ValueError: shapes (4,1) and (4,1) not aligned: 1 (dim 1) != 4 (dim 0)

In [7]:
# is there a magnitude?
zz.size

4

In [8]:
# matrice won't work
# Lets try array
yy = np.array([1,2,3,4])
yy

array([1, 2, 3, 4])

In [9]:
yy.dot(yy)

30

In [10]:
np.sqrt(9)

3.0

Gram Schmidt Process:

1. Start with "random" vectors r1, r2, r3, and r4.
2. Process them in order, generating: u1, u2, u3, and u4.

After each step, we'll check that our nice vectors are:
*Orthogonal to previous nice vectors
*have magnitude of 1

In [11]:
# These are the "random vectors"
r1= np.array( [3,0,3,0])
print("r1 is", r1)

r2= np.array( [3,2,3,3])
print("r2 is", r2)

r3= np.array( [-7,-4,-5,-6])
print("r3 is", r3)

r4= np.array( [-7,-3,-11,2])
print("r4 is", r4)

r1 is [3 0 3 0]
r2 is [3 2 3 3]
r3 is [-7 -4 -5 -6]
r4 is [ -7  -3 -11   2]


In [12]:
# Let's process the vectors:
  # Select a random vector, and subtract the nice pieces.
  #   t= r - ____ u1 - ____ u2 - ____ u3.....
  #       Where the ____

In [13]:
#Process r1:
t1 = r1
print("t1 = ", t1)

#Magnitude
n1 = np.sqrt (t1.dot(t1))
print("the size of t1 is ", n1)
#create u1:
u1 = (1/n1)*t1
print("u1 is ", u1)

t1 =  [3 0 3 0]
the size of t1 is  4.242640687119285
u1 is  [0.70710678 0.         0.70710678 0.        ]


In [14]:
# sanity check:
print("the size of u1 is ", np.sqrt(u1.dot(u1)))

the size of u1 is  1.0


In [15]:
#Process r2:
t2 = r2 - (r2.dot(u1)) *u1
print("t2 = ", t2)

#Magnitude
n1 = np.sqrt (t2.dot(t2))
print("the size of t2 is ", n1)
#create u2:
u2 = (1/n1)*t2
print("u2 is ", u2)

t2 =  [-4.4408921e-16  2.0000000e+00 -4.4408921e-16  3.0000000e+00]
the size of t2 is  3.605551275463989
u2 is  [-1.23168186e-16  5.54700196e-01 -1.23168186e-16  8.32050294e-01]


In [16]:
(5.54700196e-01)*(5.54700196e-01)

0.3076923074424384

In [17]:
2/np.sqrt(13)

0.5547001962252291

In [18]:
# sanity check:
print("the size of u2 is ", np.sqrt(u2.dot(u2)))

print("the dot product of u1 and u2 is ", u2.dot(u1))

the size of u2 is  1.0
the dot product of u1 and u2 is  -1.741861189847285e-16


In [19]:
#Process r3:
t3 = r3 -(r3.dot(u1)) *u1 -(r3.dot(u2)) *u2
print("t3 = ", t3)

#Magnitude
n1 = np.sqrt (t3.dot(t3))
print("the size of t3 is ", n1)
#create u3:
u3 = (1/n1)*t3
print("u3 is ", u3)

t3 =  [-1.0000000e+00 -4.4408921e-16  1.0000000e+00 -8.8817842e-16]
the size of t3 is  1.4142135623730951
u3 is  [-7.07106781e-01 -3.14018492e-16  7.07106781e-01 -6.28036983e-16]


In [21]:
# sanity check:
print("the size of u3 is ", np.sqrt(u3.dot(u3)))

np.dot(u3,u2)


the size of u3 is  0.9999999999999999


-6.967444759389139e-16

In [27]:
#Process r4:
t4 = r4 -(r4.dot(u1)) *u1 -(r4.dot(u2)) *u2 - (r4.dot(u3)) * u3
print("t4 = ", t4)

#Magnitude
n1 = np.sqrt (t4.dot(t4))
print("the size of t4 is ", n1)
#create u4:
u4 = (1/n1)*t4
print("u4 is ", u4)

t4 =  [ 0. -3.  0.  2.]
the size of t4 is  3.605551275463989
u4 is  [ 0.         -0.83205029  0.          0.5547002 ]


In [28]:
u4.dot(u3)

-8.709305949236341e-17